import numpy as np
import pandas as pd


def impute_missing(
    df: pd.DataFrame,
    method: str = "ffill",
) -> pd.DataFrame:
    """
    Imputes missing values according to the chosen method.

    Method retained in the study: forward fill (ffill), which avoids
    any look-ahead bias unlike linear interpolation
    (see notebook 01, section 2.4: ffill vs interpolation comparison).
    Residual NaNs at the start of the series are dropped.

    Parameters
    ----------
    df : pd.DataFrame
        Price DataFrame with potential missing values.
    method : str
        "ffill" (retained in the study) or "interpolate".

    Returns
    -------
    pd.DataFrame
        DataFrame with no missing values.
    """

    if method == "ffill":
        df_imputed = df.ffill()
    elif method == "interpolate":
        df_imputed = df.interpolate(method="linear")
    else:
        raise ValueError(f"Unknown imputation method: {method}")

    df_imputed = df_imputed.dropna()

    return df_imputed


def add_log_returns(
    df: pd.DataFrame,
    price_cols: list[str],
) -> pd.DataFrame:
    """
    Adds log_<col> and dlog_<col> for each price column.

    Reproduces the transformation applied in notebooks 01 and 03:
    log-price to stabilize variance, then first difference
    (logarithmic return) to obtain stationary I(0) series
    from I(1) series.

    Note: for us10y (a rate, already in levels rather than a price),
    the notebook takes the difference directly (dus10y = us10y.diff())
    without going through the log - to be handled separately if needed,
    this function assumes "price"-type columns (gold, silver, dollar
    index).

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing the price columns.
    price_cols : list[str]
        Names of the price columns to transform (e.g., ["gold", "silver"]).

    Returns
    -------
    pd.DataFrame
        DataFrame enriched with the log_<col> and dlog_<col> columns.
    """

    df_out = df.copy()

    for col in price_cols:
        df_out[f"log_{col}"] = np.log(df_out[col])
        df_out[f"dlog_{col}"] = df_out[f"log_{col}"].diff()

    return df_out


def add_log_ratio(
    df: pd.DataFrame,
    col_a: str = "log_gold",
    col_b: str = "log_silver",
    name: str = "log_ratio",
) -> pd.DataFrame:
    """
    Adds the log-ratio (spread) between two log series.

    log_ratio = log(A) - log(B) = log(A / B)

    Used in the study as an indicator of the relative gold/silver
    gap (see notebook 01, cell 18). Assumes col_a and col_b already
    exist in df (generated by add_log_returns).

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing col_a and col_b.
    col_a, col_b : str
        Log columns to subtract (default log_gold, log_silver).
    name : str
        Name of the created column.

    Returns
    -------
    pd.DataFrame
        DataFrame enriched with the log_ratio column.
    """

    df_out = df.copy()
    df_out[name] = df_out[col_a] - df_out[col_b]

    return df_out


def clean_for_model(
    df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Replaces infinite values with NaN, then drops incomplete observations.

    Step systematically applied before every econometric test in the
    study (ADF, Engle-Granger, Johansen, VAR/VECM) via the
    `.replace([np.inf, -np.inf], np.nan).dropna()` pattern repeated
    throughout the notebook. Log-returns can produce +/-inf if a
    price is zero or negative upstream (edge case, kept as a
    safeguard).

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame potentially enriched with log-prices / returns.

    Returns
    -------
    pd.DataFrame
        Clean DataFrame, free of inf and NaN.
    """

    df_clean = df.replace([np.inf, -np.inf], np.nan).dropna()

    return df_clean


def train_val_test_split(
    df: pd.DataFrame,
    train_frac: float = 0.70,
    val_frac: float = 0.85,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Chronologically splits the data into train, validation and test sets.

    70/15/15 split used throughout the study (see notebooks 01 and 03,
    "split" sections), with no shuffling, since the data are time
    series: chronological order must be preserved to avoid any
    look-ahead bias.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame sorted by date (time index).
    train_frac : float
        Cumulative fraction marking the end of the training sample
        (0.70 = 70%).
    val_frac : float
        Cumulative fraction marking the end of the validation sample
        (0.85 = 70%+15%).

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]
        (df_train, df_val, df_test)
    """

    n = len(df)
    train_end = int(n * train_frac)
    val_end = int(n * val_frac)

    df_train = df.iloc[:train_end].copy()
    df_val = df.iloc[train_end:val_end].copy()
    df_test = df.iloc[val_end:].copy()

    return df_train, df_val, df_test


def save_processed(df: pd.DataFrame, filename: str, output_dir: str = "../data/processed") -> None:
    """Saves the transformed data (ready for analysis)."""
    path = f"{output_dir}/{filename}"
    df.to_csv(path)
    print(f"Transformed data saved: {path}")